# Адрес и порт, на котором будет работать наш DNS-фильтр.
# 0.0.0.0 означает "слушать на всех сетевых интерфейсах".
listen_address: "0.0.0.0:53"

# Адрес DNS-сервера, на который будут перенаправляться разрешённые запросы.
forwarder_address: "8.8.8.8:53"

# Путь к папке с файлами чёрных списков (.txt).
blacklists_dir: "blacklists"

# Уровень логирования: "info" или "debug".
log_level: "info"